name: Environment and Script Check

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  check-environment-and-run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: false
          activate-environment: anomllm

      - name: Create Conda environment and install dependencies
        shell: bash -l {0}
        run: |
          conda activate anomllm
          pip install poetry
          poetry install

      - name: Save credentials
        run: echo "${{ secrets.CREDENTIALS }}" > credentials.yml

      - name: Convert Jupyter notebook to Python script
        run: |
          pip install nbconvert
          jupyter nbconvert --to script notebook/example.ipynb

      - name: Run converted script
        shell: bash -l {0}
        run: |
          conda activate anomllm
          python notebook/example.py
